apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sriovacceleratornodepolicies.sriovnetwork.openshift.io
spec:
  group: sriovnetwork.openshift.io
  names:
    kind: SriovAcceleratorNodePolicy
    listKind: SriovAcceleratorNodePolicyList
    plural: sriovacceleratornodepolicies
    singular: sriovacceleratornodepolicy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: SriovAcceleratorNodePolicy is the Schema for the sriovacceleratornodepolicies
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SriovNetworkNodePolicySpec defines the desired state of SriovAcceleratorNodePolicy
            properties:
              accelSelector:
                description: AccelSelector selects the PCI to be configured
                properties:
                  deviceID:
                    description: The device hex code of SR-IoV device. Allowed value
                      "158b", "1015", "1017".
                    type: string
                  rootDevices:
                    description: PCI address of SR-IoV PF.
                    items:
                      type: string
                    type: array
                  vendor:
                    description: The vendor hex code of SR-IoV device. Allowed value
                      "8086", "15b3".
                    type: string
                type: object
              config:
                description: Config configure the accelerator card
                type: string
              deviceName:
                description: DeviceName selects the config_bbdev code, Allowed value
                  "FPGA_LTE", "FPGA_5GNR"
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                description: NodeSelector selects the nodes to be configured
                type: object
              numVfs:
                description: Number of VFs for each PF
                minimum: 0
                type: integer
              priority:
                description: Priority of the policy, higher priority policies can
                  override lower ones.
                maximum: 99
                minimum: 0
                type: integer
              resourceName:
                description: SRIOV Accelerator device plugin endpoint resource name,
                type: string
            required:
            - accelSelector
            - config
            - deviceName
            - nodeSelector
            - numVfs
            - resourceName
            type: object
          status:
            description: SriovAcceleratorNodePolicyStatus defines the observed state
              of SriovAcceleratorNodePolicy
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
